### ISSUE TITLE
Иногда отваливается 1 из каналов при gitter:pool

### ISSUE THREAD

**Issue by Big-Shark** [LaravelRUS/GitterBot#30]
В тестовом канале все работает, но в основном бот молчит.

**Comment by SerafimArts** [comment]
Это печально, я даже не знаю почему =(

**Comment by SerafimArts** [comment]
### Стектрейс этой проблемы

``` bash
production.ERROR: An error occurred in the underlying stream in ~/vendor/react/http-client/src/Request.php:172
#0 ~/vendor/react/promise/src/RejectedPromise.php(37): React\HttpClient\Request->handleError(Object(React\SocketClient\ConnectionException))
#1 ~/vendor/react/promise/src/Promise.php(51): React\Promise\RejectedPromise->done(Object(Closure), Array)
#2 ~/vendor/react/promise/src/Promise.php(159): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#3 ~/vendor/react/promise/src/Promise.php(137): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#4 ~/vendor/react/promise/src/Promise.php(180): React\Promise\Promise->reject(Object(React\SocketClient\ConnectionException))
#5 ~/vendor/react/promise/src/RejectedPromise.php(37): React\Promise\Promise->React\Promise\{closure}(Object(React\SocketClient\ConnectionException))
#6 ~/vendor/react/promise/src/Promise.php(115): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#7 ~/vendor/react/promise/src/Promise.php(159): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#8 ~/vendor/react/promise/src/Promise.php(137): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#9 ~/vendor/react/promise/src/Promise.php(180): React\Promise\Promise->reject(Object(React\SocketClient\ConnectionException))
#10 ~/vendor/react/promise/src/RejectedPromise.php(37): React\Promise\Promise->React\Promise\{closure}(Object(React\SocketClient\ConnectionException))
#11 ~/vendor/react/promise/src/Promise.php(115): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#12 ~/vendor/react/promise/src/Promise.php(159): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#13 ~/vendor/react/promise/src/Promise.php(137): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#14 ~/vendor/react/promise/src/Promise.php(180): React\Promise\Promise->reject(Object(React\SocketClient\ConnectionException))
#15 ~/vendor/react/promise/src/RejectedPromise.php(37): React\Promise\Promise->React\Promise\{closure}(Object(React\SocketClient\ConnectionException))
#16 ~/vendor/react/promise/src/Promise.php(115): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#17 ~/vendor/react/promise/src/Promise.php(159): React\Promise\Promise->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#18 ~/vendor/react/promise/src/Promise.php(128): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#19 ~/vendor/react/promise/src/Promise.php(177): React\Promise\Promise->resolve(Resource id #652)
#20 [internal function]: React\Promise\Promise->React\Promise\{closure}(Resource id #652)
#21 ~/vendor/react/promise/src/Deferred.php(35): call_user_func(Object(Closure), Resource id #652)
#22 ~/vendor/react/socket-client/src/Connector.php(72): React\Promise\Deferred->resolve(Resource id #652)
#23 [internal function]: React\SocketClient\Connector->React\SocketClient\{closure}(Resource id #652, Object(React\EventLoop\StreamSelectLoop))
#24 ~/vendor/react/event-loop/StreamSelectLoop.php(235): call_user_func(Object(Closure), Resource id #652, Object(React\EventLoop\StreamSelectLoop))
#25 ~/vendor/react/event-loop/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(642233.13331604)
#26 ~/app/Gitter/Client.php(207): React\EventLoop\StreamSelectLoop->run()
#27 ~/app/Console/Commands/StartGitterBot.php(91): App\Gitter\Client->run()
#28 [internal function]: App\Console\Commands\StartGitterBot->handle(Object(Illuminate\Config\Repository), Object(Illuminate\Foundation\Application))
#29 ~/bootstrap/cache/compiled.php(1181): call_user_func_array(Array, Array)
#30 ~/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#31 ~/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 ~/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 ~/vendor/symfony/console/Application.php(878): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 ~/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\StartGitterBot), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 ~/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 ~/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 ~/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 {main}
```

**Comment by SerafimArts** [comment]
В режиме тестирования: https://github.com/LaravelRUS/GitterBot/commit/7eecb466882adaaa3c47bb43624de841983c1494
